# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml
build:
  maxIssues: 1000

formatting:
  maxIssues: 1000
  autoCorrect: yes
